// Code generated by Slice Machine. DO NOT EDIT.

import Embed from './Embed';
import NavItem from './NavItem';
import RichText from './RichText';

export {
	Embed,
	NavItem,
	RichText,
};

export const components = {
	embed: Embed,
	nav_item: NavItem,
	rich_text: RichText,
};
