// Code generated by Slice Machine. DO NOT EDIT.

import Collapsible from './Collapsible';
import Embed from './Embed';
import NavItem from './NavItem';
import RichText from './RichText';

export {
	Collapsible,
	Embed,
	NavItem,
	RichText,
};

export const components = {
	collapsible: Collapsible,
	embed: Embed,
	nav_item: NavItem,
	rich_text: RichText,
};
